AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Venafi-WebSDK-Python

  Sample SAM Template for Venafi-WebSDK-Python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  VenafiPyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: venafi_websdk/
      Handler: tpp.lambda_handler
      Runtime: python3.7
      Events:
        TPP:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /policy
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TPPApi:
    Description: "API Gateway endpoint URL for Prod stage for TPP WebSDK function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/policy/"
  VenafiPyFunction:
    Description: "TPP WebSDK Lambda Function ARN"
    Value: !GetAtt VenafiPyFunction.Arn
  VenafiPyFunctionIamRole:
    Description: "Implicit IAM Role created for TPP WebSDK function"
    Value: !GetAtt VenafiPyFunctionRole.Arn
